# Generated by Django 5.1.4 on 2026-05-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_weight', models.FloatField(verbose_name='Bemor vazni (kg)')),
                ('patient_age', models.IntegerField(verbose_name='Bemor yoshi (yil)')),
                ('drug_name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('route', models.CharField(choices=[('oral', "Og'iz orqali (Tabletka)"), ('injection', 'Ukol (Injection)'), ('infusion', 'Kapelnitsa (Infusion)')], max_length=20, verbose_name='Yuborish usuli')),
                ('dose', models.FloatField(verbose_name='Doza (mg)')),
                ('model_type', models.CharField(choices=[('one', 'Bir kamerali model'), ('two', 'Ikki kamerali model')], max_length=10, verbose_name='Model turi')),
                ('k', models.FloatField(default=0.1, verbose_name='k — eliminatsiya (1/soat)')),
                ('ka', models.FloatField(default=1.2, verbose_name='ka — absorbsiya (1/soat)')),
                ('ke', models.FloatField(default=0.1, verbose_name='ke — eliminatsiya (1/soat)')),
                ('mic', models.FloatField(default=2.0, verbose_name='MIC (mg/L)')),
                ('mtc', models.FloatField(default=10.0, verbose_name='MTC (mg/L)')),
                ('t_end', models.FloatField(default=24.0, verbose_name="Vaqt oralig'i (soat)")),
                ('h', models.FloatField(default=1.0, verbose_name='Vaqt qadami (soat)')),
                ('risk_status', models.CharField(blank=True, choices=[('toxic', 'Toksik'), ('subtherapeutic', 'Terapevtik darajadan past'), ('safe', 'Xavfsiz')], max_length=20, verbose_name='Xavf holati')),
                ('max_concentration', models.FloatField(blank=True, null=True, verbose_name='Maksimal konsentratsiya')),
                ('next_dose_time', models.FloatField(blank=True, null=True, verbose_name='Keyingi doza vaqti (soat)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hisoblash',
                'verbose_name_plural': 'Hisoblashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Umumiy nomi')),
                ('k_default', models.FloatField(default=0.1, verbose_name='Eliminatsiya konstantasi k (1/soat)')),
                ('ka_default', models.FloatField(default=1.2, verbose_name='Absorbsiya konstantasi ka (1/soat)')),
                ('ke_default', models.FloatField(default=0.1, verbose_name='Eliminatsiya konstantasi ke (1/soat)')),
                ('mic', models.FloatField(default=2.0, verbose_name='Minimal terapevtik chegara (mg/L)')),
                ('mtc', models.FloatField(default=10.0, verbose_name='Maksimal toksik chegara (mg/L)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('category', models.CharField(blank=True, choices=[('antibiotic', 'Antibiotik'), ('analgesic', "Og'riq qoldiruvchi"), ('antihypertensive', 'Gipertoniyaga qarshi'), ('antidiabetic', 'Diabetga qarshi'), ('cardiac', 'Yurak dori'), ('other', 'Boshqa')], max_length=100, verbose_name='Kategoriya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
                'ordering': ['name'],
            },
        ),
    ]
